# Generated by Django 3.0.1 on 2019-12-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('general', 'GENERAL'), ('immunology', 'IMMUNOLOGY'), ('dermatology', 'DERMATOLOGY'), ('internal-medicine', 'INTERNAL-MEDICINE'), ('neurology', 'NEUROLOGY'), ('gynecology', 'GYNECOLOGY'), ('ophthalmology', 'OPHTHALMOLOGY'), ('pediatrics', 'PEDIATRICS'), ('psychiatry', 'PSYCHIATRY')], default='general', max_length=25)),
                ('address', models.CharField(max_length=300, null=True)),
                ('area', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(choices=[('cairo', 'CAIRO'), ('alexandria', 'ALEXANDRIA')], max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='media/images/drs')),
                ('Featured', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
    ]
