# Generated by Django 3.0.1 on 2019-12-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
