# Generated by Django 3.0.1 on 2020-01-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='city',
            field=models.CharField(choices=[('CAI', 'Cairo'), ('ALEX', 'Alexandira')], max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('general', 'GENERAL'), ('immunology', 'IMMUNOLOGY'), ('dermatology', 'DERMATOLOGY'), ('internal-medicine', 'INTERNAL-MEDICINE'), ('neurology', 'NEUROLOGY'), ('gynecology', 'GYNECOLOGY'), ('ophthalmology', 'OPHTHALMOLOGY'), ('pediatrics', 'PEDIATRICS'), ('psychiatry', 'PSYCHIATRY')], default='general', max_length=50),
        ),
    ]
