# Generated by Django 3.0.1 on 2020-01-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200111_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='city',
            field=models.CharField(choices=[('cairo', 'Cairo'), ('alexandria', 'Alexandira')], max_length=100),
        ),
    ]
