# Generated by Django 3.0.1 on 2020-01-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200112_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='city',
            field=models.CharField(choices=[('Cairo', 'cairo'), ('Alexandria', 'alexandira')], max_length=100),
        ),
    ]
